# version: "3.4"

services:
  postgres:
    container_name: chat-db-graphql
    image: postgres
    ports:
      - 5430:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: chatdb_graphql
      POSTGRES_PASSWORD: admin

volumes:
  postgres_data: